---
title: "Generate Data for Exercises"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
```


You don't need to look at this! It simulates experimental data that we can practice with!

# Exercise 1

```{r}
set.seed(1)
mean_control=15000
mean_treated=12000
sd_both=1000
n_measurements=3

cell_treatment_data<-data.frame(Treatment=c(rep("Control",n_measurements),rep("Treated",n_measurements)),
                                Metabolic_Activity=c(rnorm(n_measurements,mean_control,sd_both),rnorm(n_measurements,mean_treated,sd_both)))

cell_treatment_data %<>% mutate(Metabolic_Activity=round(Metabolic_Activity))

write_csv(cell_treatment_data,"cell_treatment_data.csv")
```

# Exercise 2

```{r}
set.seed(1)
gradient=0.0006
intercept=0.18

protein_ug_ml<-c(0,250,500,1000,1500,2000)
error<-rnorm(length(protein_ug_ml),sd=0.1)
OD_600<-gradient*protein_ug_ml+intercept+error

assay_calibration_data<-data.frame(protein_ug_ml,OD_600)

write_csv(assay_calibration_data,"assay_calibration_data.csv")
```

